# -*- coding: utf-8 -*-
"""Calculation_Deo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_0sIUNpWfaxFOqwiOJCg6cKWHf7peU1p
"""

import numpy as np
import xarray as xr

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

for year_i in range(1981,1986):
  print(year_i)
  for month_i in range(1, 13):

    stmax_daily = xr.open_dataset(path_netcd_01+"S/Stmax/Stmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    stmin_daily = xr.open_dataset(path_netcd_01+"S/Stmin/Stmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    sea_daily = xr.open_dataset(path_netcd_01+"S/Sea/Sea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    srn_daily = xr.open_dataset(path_netcd_01+"S/Srn/Srn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    sws_daily = xr.open_dataset(path_netcd_01+"S/Sws/Sws_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc") 
    ses_daily = xr.open_dataset(path_netcd_01+"S/Ses/Ses_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    sdelta_daily = xr.open_dataset(path_netcd_01+"S/Sdelta/Sdelta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
   
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    delta_eo = stmax_daily.Stmax*eo_daily.eo + stmin_daily.Stmin*eo_daily.eo + sea_daily.Sea*eo_daily.eo + srn_daily.Srn*eo_daily.eo + sws_daily.Sws*eo_daily.eo + ses_daily.Ses*eo_daily.eo + sdelta_daily.Sdelta*eo_daily.eo
  
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Deo"]}
    delta_eo.to_dataset(name="Deo").to_netcdf(path_netcd_01+"Deo_c/Deo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')

delta_eo.isel(time=15).plot()

delta_eo.isel(time=15).where(delta_eo.isel(time=15) < 0).plot()

year_i = 1981
month_i = 1
ses_daily = xr.open_dataset(path_netcd_01+"S/Ses/Ses_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

ses_daily.isel(time=20).Ses.plot()

