# -*- coding: utf-8 -*-
"""calculation_mean_Deo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_6Nyia6tkRzZT_VdjGNqksdz-4C88MBW
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install glob

import glob
import xarray as xr

path_save_file="/content/drive/MyDrive/Deo_clim/"

"""## Mean monthly average of Deo (1981-2016)"""

Deo_files = sorted(glob.glob("/content/drive/MyDrive/DATA_FT/version_rc/Deo_c/*.nc"))

Deo_monthly_var_mean = []
for month_i in range(1, 13):
    print(month_i)
    month_files = [string for string in Deo_files if str(month_i).zfill(2) in string.split("_")[5].split(".")[0]]
    month_files = xr.concat([xr.open_dataset(file).mean(dim="time") for file in month_files], dim="time")
    Deo_monthly_var_mean.append(month_files.mean(dim="time"))

Deo_monthly_var_mean = (xr.concat(Deo_monthly_var_mean, dim="month"))

# save
encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Deo"]}
Deo_monthly_var_mean.to_netcdf(path_save_file+"Deo_monthly_mean_clim.nc", encoding=encoding, engine='netcdf4')

"""## Mean annual average of Deo (1981-2016)"""

Deo_annual_var_mean = []
for year_i in range(1981,2017):
    print(year_i)
    year_files = [string for string in Deo_files if str(year_i) in string.split("_")[5]]
    year_files = xr.concat([xr.open_dataset(file).mean(dim="time") for file in year_files], dim="time")
    Deo_annual_var_mean.append(year_files.mean(dim="time"))

Deo_annual_var_mean = (xr.concat(Deo_annual_var_mean, dim="time")).mean(dim="time")

# save
encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Deo"]}
Deo_annual_var_mean.to_netcdf(path_save_file+"Deo_annual_mean_clim.nc", encoding=encoding, engine='netcdf4')

