# -*- coding: utf-8 -*-
"""Deltaeo_overview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7aaejV0zilHGbrlXM3ggRHEXosy6Af8

Derivates of FAO-PM based on sub-variables:
*   [FAO_Penman_Monteith_equation_derivates](https://colab.research.google.com/drive/1EfcfWV5KdZaOKvlP52y9VseVbQEnPLss?usp=sharing)

Minimum value each sub-variable


*   [min_value](https://colab.research.google.com/drive/1qvp3YLK_SquGxCuv2A_Al8IsPqUe7tp1?usp=sharing)

Example Eo

*   [example_Eocal_PiscoEo](https://colab.research.google.com/drive/1rrdyLtg7OitXcb8YvqCK3AxSGfKAa4p8?usp=sharing)

Example of S/ΔEo for one day:


*   [example_S_Deo](https://colab.research.google.com/drive/1AJ3vq0Rl0n8NP6OSJOipXGpVFbpakK5x?usp=sharing) 
*   [example_Deo_version_2](https://colab.research.google.com/drive/1wrLjHwu2jb89sGfbjAPDmJ9NcIHfZqKi?usp=sharing)

S for each sub-variable pre-processing:
*   [S_tmax](https://colab.research.google.com/drive/1BKCF28TN8ICG3o2A4j0q_pqoFHqHWpLw?usp=sharing)
*   [S_tmin](https://colab.research.google.com/drive/1phD5TepVlmHqY15Lwl4SGsgpVd2LoSQD?usp=sharing)
*   [S_ea](https://colab.research.google.com/drive/1RExD3r1LnLgpyit5WcrDBWQWKQtU85K5?authuser=1#scrollTo=D95SbUqWvjwa)
*   [S_rn](https://colab.research.google.com/drive/1ThyWReAn4V95aHXuEKMFFcW0vJ77ti77?authuser=1#scrollTo=expLScK8A6PM)
*   [S_u2](https://colab.research.google.com/drive/11GOzKTfvHuPK6JGDvWBaUmokUK9L1YKC?authuser=1#scrollTo=ZqQOsykDBbRs)
*   [S_es](https://colab.research.google.com/drive/1kbMoZ9uCT7hXYa3LdXjdffl8FxlZR_AY?usp=sharing)
*   [S_DELTA](https://colab.research.google.com/drive/1IW7UJPmrxnIXPifD63DViQGxsLqS4rNx?usp=sharing)

Estimation mean S/ΔEo monthly and annual


*   [Calculation_mean_sensitivity](https://colab.research.google.com/drive/17GbENwyYIhYyEqiKsn9KEIkomZJy5qX9?usp=sharing)

*   [Calculation_mean_Deo](https://colab.research.google.com/drive/1_6Nyia6tkRzZT_VdjGNqksdz-4C88MBW?usp=sharing)

ΔEo estimation (based on S):
*   [Calculation_Deo](https://colab.research.google.com/drive/1_0sIUNpWfaxFOqwiOJCg6cKWHf7peU1p?usp=sharing)

Figures 

*S*
*   [Figures_spatial_variability](https://colab.research.google.com/drive/1d1J04yJTU9Ip5uUQzMSR3sESUsXcMqks?usp=sharing)
*   [Figures_temporal_variability](https://colab.research.google.com/drive/1f48hYWXqjtTt8RiDb8AB72RcxJR33PRE?usp=sharing)

*ΔEo*


*   [Figures_spatial_variability](https://colab.research.google.com/drive/1iIPvj5TkC6uq-facfocsRT8OK-TXN41v?usp=sharing)
*   [Figures_temporal_variability](https://colab.research.google.com/drive/1t00TyK8frgbgteJ-Wzh1bol6vZPqr1TC?usp=sharing)
"""

