# -*- coding: utf-8 -*-
"""example_Deo_version_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrLjHwu2jb89sGfbjAPDmJ9NcIHfZqKi
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import xarray as xr
import numpy as np

# Define time
year_i=1981
month_i=1
day_i=1

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc")
ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
es_daily = xr.open_dataset(path_netcd_01+"es/daily/es_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")  
rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

DDELTA = xr.open_dataset(path_netcd_01+"D/DDELTA/DDELTA_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Dws = xr.open_dataset(path_netcd_01+"D/Dws/Dws_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Dea = xr.open_dataset(path_netcd_01+"D/Dea/Dea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Des = xr.open_dataset(path_netcd_01+"D/Des/Des_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Dtmax = xr.open_dataset(path_netcd_01+"D/Dtmax/Dtmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Dtmin = xr.open_dataset(path_netcd_01+"D/Dtmin/Dtmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
Drn = xr.open_dataset(path_netcd_01+"D/Drn/Drn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

var_delta = (np.power(DDELTA.DDELTA, 2).isel(time=5)*delta_daily.var(dim="time")).delta
var_ws = (np.power(Dws.Dws, 2).isel(time=5)*ws_daily.var(dim="time")).ws 
var_ea = (np.power(Dea.Dea, 2).isel(time=5)*ea_daily.var(dim="time")).ea
var_es = (np.power(Des.Des, 2).isel(time=5)*es_daily.var(dim="time")).es
var_tmax = (np.power(Dtmax.Dtmax, 2).isel(time=5)*tmax_daily.var(dim="time")).tmax
var_tmin = (np.power(Dtmin.Dtmin, 2).isel(time=5)*tmin_daily.var(dim="time")).tmin
var_rn = (np.power(Drn.Drn, 2).isel(time=5)*rn_daily.var(dim="time")).rn

var_eo =  var_delta + var_ws + var_ea + var_es + var_tmax + var_tmin + var_rn

adr = var_eo

adr2 = var_eo

(adr - adr2).plot()

