# -*- coding: utf-8 -*-
"""FAO_Penman_Monteith_equation_derivates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EfcfWV5KdZaOKvlP52y9VseVbQEnPLss
"""

from sympy import *

# variables Penman Monteith
DELTA = Symbol('DELTA')
GAMMA = Symbol("GAMMA")
Rn = Symbol("Rn")
G = Symbol("G")
Tx = Symbol("Tx")
Tn = Symbol("Tn")
u2 = Symbol("u2")
es = Symbol("es")
ea = Symbol("ea")

# Penman Monteith FAO56 equation
#f = (0.408*DELTA*(Rn-G) + GAMMA*(900/(((Tx+Tn)/2)+273))*u2*(es-ea))/(DELTA + GAMMA*(1+0.34*u2))
f = (0.408*DELTA*(Rn) + GAMMA*(900/(((Tx+Tn)/2)+273))*u2*(es-ea))/(DELTA + GAMMA*(1+0.34*u2))

# Tx = Maximum temperature
f.diff(Tx)

# Tn = Minimum temperature
f.diff(Tn)

# ea = Actual vapor pressure
f.diff(ea)

# Rn = Net radiation
f.diff(Rn)

# u2 = Wind speed
f.diff(u2)

# es = mean saturated vapor pressure
f.diff(es)

# DELTA = Slope of saturation vapor pressure curve
f.diff(DELTA)

# GAMMA is constant