# -*- coding: utf-8 -*-
"""figures_temporal_variability_Deo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t00TyK8frgbgteJ-Wzh1bol6vZPqr1TC
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install geopandas
# !pip install rioxarray

import rioxarray
import pandas as pd
from geopandas import read_file as gpd_read_file
import xarray as xr
import matplotlib.pyplot as plt
from numpy import isnan as np_isnan

path_save_file ="/content/drive/MyDrive/Deo_clim/"

Deo_monthly_var_mean= xr.open_dataset(path_save_file+"Deo_monthly_mean_clim.nc")

shp_Peru = gpd_read_file('/content/drive/MyDrive/shapes_colab/SEC_CLIM.shp')
shp_Peru = shp_Peru.dissolve(by="MAC_REG")

shp_Peru

# required functions
def xr_crop(shp_i, netcdf_i):
  # get box
  box_i = shp_i.total_bounds
  
  # crop based on box
  crop_netcdf_i = netcdf_i.where((netcdf_i["longitude"] > box_i[0]) & # min lon
                                 (netcdf_i["longitude"] < box_i[2]) & # max lon
                                 (netcdf_i["latitude"] > box_i[1]) & # min lat
                                 (netcdf_i["latitude"] < box_i[3]), # max lat
                                 drop = True)
  
  return crop_netcdf_i

def xr_shp_to_grid(shp_i, netcdf_array):

  # get real box
  shp_i_geometry = shp_i.geometry

  # adding crs
  mask = netcdf_array.rio.set_crs(shp_i.crs)

  # "rasterizing"
  mask = mask.rio.clip(shp_i_geometry, drop = False)

  # making "True/False" values
  mask.values[~np_isnan(mask.values)] = 1

  return mask.drop([ "spatial_ref"])

def xr_mask(grid_mask, netcdf_i):

  # masking
  mask_netcdf_i = netcdf_i.where(grid_mask == True)

  return mask_netcdf_i

def ext_mask(netcdf_file, shape, variable):
    netcdf_cropped = xr_crop(shp_i = shape, 
                         netcdf_i = netcdf_file)
    shp_exp_grid = xr_shp_to_grid(shp_i = shape, 
                              netcdf_array = netcdf_cropped.isel(month=0)[variable])
    netcdf_masked = xr_mask(grid_mask = shp_exp_grid,
                              netcdf_i = netcdf_cropped)
    return netcdf_masked

#crop netcdf to shape region and calculate mean 
def S_monthlyclim(variable, S_var ):

    S_monthly_clim = []
  
    for reg in range(0,5) :
        Reg_S = ext_mask(variable,shp_Peru.iloc[[reg]],S_var)
        Reg_S = Reg_S.mean(dim=["latitude", "longitude"]).to_dataframe()
        S_monthly_clim.append(Reg_S) 
    S_monthly_clim=pd.concat( S_monthly_clim, axis=1)
    S_monthly_clim.columns = ['CO', 'SEA', 'SEB', 'SIOC', 'SIOR']
    return S_monthly_clim

shp_Peru.iloc[[0]]

shp_Peru.iloc[[1]]

shp_Peru.iloc[[2]]

shp_Peru.iloc[[3]]

shp_Peru.iloc[[4]]

"""### Figure: Monthly mean variability Deo for each climate zone"""

fig, ax1 = plt.subplots(figsize=(7, 5), dpi = 100)

Deo_monthly_mean=S_monthlyclim(Deo_monthly_var_mean,"Deo")
Deo_monthly_mean=Deo_monthly_mean.set_index(pd.Index(range(1,13)))
Deo_monthly_mean.plot(ax=ax1)
ax1.set_title('ΔEo')
ax1.set_xlabel("meses")

plt.savefig(path_save_file + 'Deo_temporal_variability.png')

Deo_monthly_mean

"""### Table: Mean monthly average of Deo for each Climate Zone """

Deo_monthly_mean