# -*- coding: utf-8 -*-
"""S_DELTA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IW7UJPmrxnIXPifD63DViQGxsLqS4rNx
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import xarray as xr
import numpy as np

"""
# Equation
def D_DELTA(rn_i, DELTA_i, GAMMA_i, ws_i, ea_i, es_i, tmax_i, tmin_i):
  d_DELTA_d_eo = ((0.408*rn_i)/(DELTA_i + GAMMA_i*(0.34 * ws_i + 1))) - (0.408*DELTA_i*rn_i + (900*GAMMA_i*ws_i*(- ea_i + es_i)/((tmax_i/2) + (tmin_i/2) + 273)))/np.power(DELTA_i + GAMMA_i*(0.34*ws_i+1), 2)
  response = d_tmax_d_eo * ((tmax_i - tmax_min)/eo_i)
  return np.round(d_DELTA_d_eo, 2)
"""

# Equation
def S_DELTA(rn_i, DELTA_i, DELTA_min, GAMMA_i, ws_i, ea_i, es_i, tmax_i, tmin_i, eo_i):
  d_DELTA_d_eo = ((0.408*rn_i)/(DELTA_i + GAMMA_i*(0.34 * ws_i + 1))) - (0.408*DELTA_i*rn_i + (900*GAMMA_i*ws_i*(- ea_i + es_i)/((tmax_i/2) + (tmin_i/2) + 273)))/np.power(DELTA_i + GAMMA_i*(0.34*ws_i+1), 2)
  response = d_DELTA_d_eo * ((DELTA_i - DELTA_min)/eo_i)
  return np.round(response, 2)

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

for year_i in range(1989,1990):
  for month_i in range(9, 10):

    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    delta_min = xr.open_dataset("/content/drive/MyDrive/variables_min_clim/var_min_clim.nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    es_daily = xr.open_dataset(path_netcd_01+"es/daily/es_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Sdelta = xr.apply_ufunc(S_DELTA,
                            rn_daily.rn,
                           delta_daily.delta,
                            delta_min.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ea_daily.ea,
                           es_daily.es,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                            eo_daily.eo,
                           input_core_dims=[['time'], ["time"], [], [], [], ["time"], ["time"], ["time"], ["time"], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Sdelta"]}
    Sdelta.to_dataset(name="Sdelta").to_netcdf(path_netcd_01+"S/Sdelta/Sdelta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')

"""
for year_i in range(1981,1982):
  for month_i in range(1, 2):

    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    es_daily = xr.open_dataset(path_netcd_01+"es/daily/es_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    # eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    DDELTA = xr.apply_ufunc(D_DELTA,
                            rn_daily.rn,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ea_daily.ea,
                           es_daily.es,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                           input_core_dims=[['time'], ["time"], [], [], ["time"], ["time"], ["time"], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["DDELTA"]}
    DDELTA.to_dataset(name="DDELTA").to_netcdf(path_netcd_01+"D/DDELTA/DDELTA_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')
"""

