# -*- coding: utf-8 -*-
"""S_ea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RExD3r1LnLgpyit5WcrDBWQWKQtU85K5
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import xarray as xr
import numpy as np

# Equation
def S_ea(DELTA_i, GAMMA_i, ws_i, ea_i, ea_min, tmax_i, tmin_i, eo_i):
  d_ea_d_eo = (-900*GAMMA_i*ws_i)/((DELTA_i+GAMMA_i*(0.34*ws_i+1))*(tmin_i/2 + tmax_i/2 + 273))
  response = d_ea_d_eo * ((ea_i - ea_min)/eo_i)
  return np.round(response, 2)

"""
# Equation
def D_ea(DELTA_i, GAMMA_i, ws_i, ea_i, tmax_i, tmin_i, eo_i):
  d_ea_d_eo = (-900*GAMMA_i*ws_i)/((DELTA_i+GAMMA_i*(0.34*ws_i+1))*(tmin_i/2 + tmax_i/2 + 273))
  #response = d_ea_d_eo * ((ea_i - ea_min)/eo_i)
  return np.round(d_ea_d_eo, 2)
"""

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

for year_i in range(1981,1991):
  for month_i in range(1, 13):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    ea_min = xr.open_dataset("/content/drive/MyDrive/variables_min_clim/var_min_clim.nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Sea = xr.apply_ufunc(S_ea,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ea_daily.ea,
                           ea_min.ea,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                           eo_daily.eo,
                           input_core_dims=[['time'], [], [], ["time"],[], ["time"], ["time"],["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Sea"]}
    Sea.to_dataset(name="Sea").to_netcdf(path_netcd_01+"S/Sea/Sea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')

"""
for year_i in range(1981,1982):
  for month_i in range(1, 2):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")    
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Dea = xr.apply_ufunc(D_ea,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ea_daily.ea,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                           eo_daily.eo,
                           input_core_dims=[['time'], [], [], ["time"], ["time"], ["time"],["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Dea"]}
    Dea.to_dataset(name="Dea").to_netcdf(path_netcd_01+"D/Dea/Dea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')
"""

