# -*- coding: utf-8 -*-
"""S_rn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ThyWReAn4V95aHXuEKMFFcW0vJ77ti77
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import xarray as xr
import numpy as np

# Equation
def S_rn(DELTA_i, GAMMA_i, ws_i, rn_i, rn_min, eo_i):
  d_rn_d_eo = (0.408*DELTA_i)/(DELTA_i+GAMMA_i*(0.34*ws_i+1))
  response = d_rn_d_eo * ((rn_i - rn_min)/eo_i)
  return np.round(response, 2)

"""
# Equation
def D_rn(DELTA_i, GAMMA_i, ws_i, rn_i, eo_i):
  d_rn_d_eo = (0.408*DELTA_i)/(DELTA_i+GAMMA_i*(0.34*ws_i+1))
  #response = d_rn_d_eo * ((rn_i - rn_min)/eo_i)
  return np.round(d_rn_d_eo, 2)
"""

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

for year_i in range(1981,1991):
  for month_i in range(1, 13):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc") 
    rn_min = xr.open_dataset("/content/drive/MyDrive/variables_min_clim/var_min_clim.nc") 
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Srn = xr.apply_ufunc(S_rn,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           rn_daily.rn,
                           rn_min.rn,
                           eo_daily.eo,
                           input_core_dims=[['time'], [], [], ["time"], [], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Srn"]}
    Srn.to_dataset(name="Srn").to_netcdf(path_netcd_01+"S/Srn/Srn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')

"""
for year_i in range(1981,1982):
  for month_i in range(1, 2):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc") 
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Drn = xr.apply_ufunc(D_rn,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           rn_daily.rn,
                           eo_daily.eo,
                           input_core_dims=[['time'], [], [], ["time"], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Drn"]}
    Drn.to_dataset(name="Drn").to_netcdf(path_netcd_01+"D/Drn/Drn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')
"""

