# -*- coding: utf-8 -*-
"""S_ws.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GOzKTfvHuPK6JGDvWBaUmokUK9L1YKC
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import xarray as xr
import numpy as np

# Equation
def S_ws(DELTA_i, GAMMA_i, ws_i, ws_min, ea_i, es_i, tmax_i, tmin_i,rn_i, eo_i):
  d_ws_d_eo = ((900*GAMMA_i*(-ea_i+es_i))/((DELTA_i+GAMMA_i*(0.34*ws_i+1))*(tmin_i/2 + tmax_i/2 + 273)))-(0.34*GAMMA_i*(0.408*DELTA_i*(rn_i)+((900*GAMMA_i*ws_i*(-ea_i+es_i))/(tmin_i/2 + tmax_i/2 + 273)))/(np.power((DELTA_i+GAMMA_i*(0.34*ws_i+1)),2)))
  response = d_ws_d_eo * ((ws_i - ws_min)/eo_i)
  return np.round(response, 2)

"""
# Equation
def D_ws(DELTA_i, GAMMA_i, ws_i, ea_i, es_i, tmax_i, tmin_i,rn_i):
  d_ws_d_eo = ((900*GAMMA_i*(-ea_i+es_i))/((DELTA_i+GAMMA_i*(0.34*ws_i+1))*(tmin_i/2 + tmax_i/2 + 273)))-(0.34*GAMMA_i*(0.408*DELTA_i*(rn_i)+((900*GAMMA_i*ws_i*(-ea_i+es_i))/(tmin_i/2 + tmax_i/2 + 273)))/(np.power((DELTA_i+GAMMA_i*(0.34*ws_i+1)),2)))
  #response = d_ws_d_eo * ((ws_i - ws_min)/eo_i)
  return np.round(d_ws_d_eo, 2)
"""

path_netcd_01 = "/content/drive/MyDrive/DATA_FT/version_rc/"

for year_i in range(2007,2010):
  for month_i in range(1, 13):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ws_min = xr.open_dataset("/content/drive/MyDrive/variables_min_clim/var_min_clim.nc")
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    es_daily = xr.open_dataset(path_netcd_01+"es/daily/es_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")     
    eo_daily = xr.open_dataset(path_netcd_01+"eo/daily/eo_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")

    Sws = xr.apply_ufunc(S_ws,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ws_min.ws,
                           ea_daily.ea,
                           es_daily.es,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                           rn_daily.rn,
                           eo_daily.eo,
                           input_core_dims=[['time'], [], [], [], ["time"], ["time"], ["time"], ["time"], ["time"], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Sws"]}
    Sws.to_dataset(name="Sws").to_netcdf(path_netcd_01+"S/Sws/Sws_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')

"""
for year_i in range(1981,1982):
  for month_i in range(1, 2):

    delta_daily = xr.open_dataset(path_netcd_01+"delta/daily/delta_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    gamma_daily = xr.open_dataset(path_netcd_01+"gamma/gamma.nc")
    ws_daily = xr.open_dataset(path_netcd_01+"/ws/normal/ws_mean.nc").isel(time=month_i-1)
    ea_daily = xr.open_dataset(path_netcd_01+"ea/daily/ea_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    es_daily = xr.open_dataset(path_netcd_01+"es/daily/es_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmax_daily = xr.open_dataset(path_netcd_01+"tmax/daily/tmax_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    tmin_daily = xr.open_dataset(path_netcd_01+"tmin/daily/tmin_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")
    rn_daily = xr.open_dataset(path_netcd_01+"rn/daily/rn_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc")     

    Dws = xr.apply_ufunc(D_ws,
                           delta_daily.delta,
                           gamma_daily.gamma,
                           ws_daily.ws,
                           ea_daily.ea,
                           es_daily.es,
                           tmax_daily.tmax,
                           tmin_daily.tmin,
                           rn_daily.rn,
                           input_core_dims=[['time'], [], [], ["time"], ["time"], ["time"], ["time"], ["time"]],
                           output_core_dims=[["time"]],
                           vectorize=True,
                           output_dtypes=['float32'])
    
    encoding = {v: {'zlib': True, 'complevel': 9} for v in ["Dws"]}
    Dws.to_dataset(name="Dws").to_netcdf(path_netcd_01+"D/Dws/Dws_daily"+"_"+str(year_i)+ "_"+str(month_i).zfill(2)+".nc", encoding=encoding, engine='netcdf4')
"""

