# -*- coding: utf-8 -*-
"""ERA5land_10_v_u.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VznW4kA-7dvTne5dAuESYZYFyyzCJUes
"""

from google.colab import drive
drive.mount('/content/drive')

# url = 'url: https://cds.climate.copernicus.eu/api/v2'
# key = 'key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# with open('/root/.cdsapirc', 'w') as f:
#     f.write('\n'.join([url, key]))

# with open('/root/.cdsapirc') as f:
#     print(f.read())

# !pip install cdsapi

# import cdsapi
# import glob
# c = cdsapi.Client()

# for year in range(1981, 2021):
#     c.retrieve("reanalysis-era5-land",
#                {
#                    "variable": "10m_v_component_of_wind",
#                    "product_type": "reanalysis",
#                    "year": str(year),
#                    'month': ['01', '02', '03',
#                              '04', '05', '06',
#                              '07', '08', '09',
#                              '10', '11', '12'],
#                    'day': ['01', '02', '03',
#                            '04', '05', '06',
#                            '07', '08', '09',
#                            '10', '11', '12',
#                            '13', '14', '15',
#                            '16', '17', '18',
#                            '19', '20', '21',
#                            '22', '23', '24',
#                            '25', '26', '27',
#                            '28', '29', '30',
#                            '31'],
#                    'time': ['00:00', '01:00', '02:00',
#                             '03:00', '04:00', '05:00',
#                             '06:00', '07:00', '08:00',
#                             '09:00', '10:00', '11:00',
#                             '12:00', '13:00', '14:00',
#                             '15:00', '16:00', '17:00',
#                             '18:00', '19:00', '20:00',
#                             '21:00', '22:00', '23:00'],
#                    "area": "2/-82/-19/-66",  # North, West, South, East
#                    "format": "netcdf"
#                },
#                "/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_v_component_of_wind/" + str(year) + ".nc")

# for year in range(1981, 2021):
#     c.retrieve("reanalysis-era5-land",
#                {
#                    "variable": "10m_u_component_of_wind",
#                    "product_type": "reanalysis",
#                    "year": str(year),
#                    'month': ['01', '02', '03',
#                              '04', '05', '06',
#                              '07', '08', '09',
#                              '10', '11', '12'],
#                    'day': ['01', '02', '03',
#                            '04', '05', '06',
#                            '07', '08', '09',
#                            '10', '11', '12',
#                            '13', '14', '15',
#                            '16', '17', '18',
#                            '19', '20', '21',
#                            '22', '23', '24',
#                            '25', '26', '27',
#                            '28', '29', '30',
#                            '31'],
#                    'time': ['00:00', '01:00', '02:00',
#                             '03:00', '04:00', '05:00',
#                             '06:00', '07:00', '08:00',
#                             '09:00', '10:00', '11:00',
#                             '12:00', '13:00', '14:00',
#                             '15:00', '16:00', '17:00',
#                             '18:00', '19:00', '20:00',
#                             '21:00', '22:00', '23:00'],
#                    "area": "2/-82/-19/-66",  # North, West, South, East
#                    "format": "netcdf"
#                },
#                "/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_u_component_of_wind/" + str(year) + ".nc")

import xarray as xr
import numpy as np
import pandas as pd
import glob
!pip install netcdf4
!pip install rasterio

# wind speed
# https://confluence.ecmwf.int/pages/viewpage.action?pageId=133262398
# http://www.fao.org/3/x0490s/x0490s.pdf (pag 56)

def uv2ws(u, v, z):

  u10 = np.sqrt(np.power(u, 2) + np.power(v, 2))
  u2 = np.around(u10*z, decimals=2)

  return u2

elevation = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/for_eo_computation/z.nc")
elevation = (4.87/np.log(67.8*elevation.z - 5.42))

for year_i in range(1981,2020):
  print(year_i)
  netcdf_year_i_u = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_u_component_of_wind/" + str(year_i) + ".nc")
  netcdf_year_i_plus_1_u = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_u_component_of_wind/" + str(year_i+1) + ".nc")
  
  netcdf_year_i_v = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_v_component_of_wind/" + str(year_i) + ".nc")
  netcdf_year_i_plus_1_v = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/10m_v_component_of_wind/" + str(year_i+1) + ".nc")
  
  netcdf_year_i_u = xr.concat([netcdf_year_i_u, netcdf_year_i_plus_1_u], dim="time")
  netcdf_year_i_u["time"] = pd.date_range(str(year_i) + '-01-01', freq="H", periods=len(netcdf_year_i_u.time)) - pd.Timedelta(hours=5)
  netcdf_year_i_u = netcdf_year_i_u.where((-82 < netcdf_year_i_u.longitude) & (netcdf_year_i_u.longitude < -67) & (-19 < netcdf_year_i_u.latitude) & (netcdf_year_i_u.latitude < 2), drop=True)
  netcdf_year_i_u = netcdf_year_i_u.sel(time=slice(str(year_i) + "-01-01", str(year_i) + "-12-31"))
  
  netcdf_year_i_v = xr.concat([netcdf_year_i_v, netcdf_year_i_plus_1_v], dim="time")
  netcdf_year_i_v["time"] = pd.date_range(str(year_i) + '-01-01', freq="H", periods=len(netcdf_year_i_v.time)) - pd.Timedelta(hours=5)
  netcdf_year_i_v = netcdf_year_i_v.where((-82 < netcdf_year_i_v.longitude) & (netcdf_year_i_v.longitude < -67) & (-19 < netcdf_year_i_v.latitude) & (netcdf_year_i_v.latitude < 2), drop=True)
  netcdf_year_i_v = netcdf_year_i_v.sel(time=slice(str(year_i) + "-01-01", str(year_i) + "-12-31"))
  
  wspeed = xr.apply_ufunc(uv2ws,
                          netcdf_year_i_u.u10,
                          netcdf_year_i_v.v10,
                          elevation,
                          vectorize=True,
                          input_core_dims=[["time"], ["time"], []],
                          output_core_dims=[["time"]],
                          output_dtypes=['float32'])
  
  wspeed = wspeed.to_dataset(name="ws")
  wspeed_var = wspeed.resample(time="1D").mean(dim="time").sel(time=slice(str(year_i) + "-01-01", str(year_i) + "-12-31")).ws
  encoding = {v: {'zlib': True, 'complevel': 5} for v in ["ws"]}
  (wspeed_var.to_dataset(name="ws")).to_netcdf("/content/drive/MyDrive/Google_Colab_temp/ERA5land/for_eo_computation/ws/ws_" + str(year_i) + ".nc", encoding=encoding, engine='netcdf4')

