# -*- coding: utf-8 -*-
"""ERA5land_elevation_and_latitude.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10O7icT7ZZzzkYNsO04h4VidgEkmfsX1f
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install netCDF4

import xarray as xr
import numpy as np
import pandas as pd
import glob
import requests

url_name_file = "https://confluence.ecmwf.int/download/attachments/140385202/geo_1279l4_0.1x0.1.grib2_v4_unpack.nc?version=1&modificationDate=1591979822003&api=v2"

with open("/content/drive/MyDrive/Google_Colab_temp/ERA5land/elevation_latitude/elevation_ERA5land.nc", "wb") as f:
  r = requests.get(url_name_file)
  f.write(r.content)

elevation = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/elevation_latitude/elevation_ERA5land.nc")
elevation.coords['longitude'] = (elevation.coords['longitude'] + 180) % 360 - 180
elevation = elevation.sortby(elevation.longitude)
elevation

elevation.z.plot()

elevation_Peru = elevation.where((-82 < elevation.longitude) & (elevation.longitude < -67) & (-19 < elevation.latitude) & (elevation.latitude < 2), drop=True)
(elevation_Peru.z/9.80665).plot()

elevation_Peru

grid_example = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/ERA5land/for_eo_computation/tmax/tmax_1981.nc")

grid_example

latitude_Peru = np.tile(elevation_Peru["latitude"].values, (149, 1)).transpose()
latitude_Peru2 = elevation_Peru.isel(time=0)
latitude_Peru2["LAT"] = (('latitude', 'longitude'), latitude_Peru)

(elevation_Peru.isel(time=0).z/9.80665).to_dataset(name="z").reindex_like(grid_example, method="nearest").to_netcdf("/content/drive/MyDrive/Google_Colab_temp/ERA5land/for_eo_computation/z.nc")

latitude_Peru2.LAT.to_dataset(name="lat").reindex_like(grid_example, method="nearest").to_netcdf("/content/drive/MyDrive/Google_Colab_temp/ERA5land/for_eo_computation/lat.nc")

(latitude_Peru2.LAT + elevation_Peru.z).plot()

