# -*- coding: utf-8 -*-
"""TerraClimate_Eo_donwload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDDof9JL98jp6XPyi7e7MvpHMzVT9_Di
"""

import xarray as xr
import numpy as np
import pandas as pd
import glob
import requests
# !pip install netcdf4
# !pip install rasterio

from google.colab import drive
drive.mount('/content/drive')

# for i in np.arange(1981, 2020):
#     name_file = "TerraClimate_pet_YI.nc".replace("YI", str(i))
#     url_name_file = "https://climate.northwestknowledge.net/TERRACLIMATE-DATA/" + name_file
#     filename = url_name_file.split("/")[-1]

#     print(filename)
#     with open("/content/drive/MyDrive/temporal/TerraClimate/" + filename, "wb") as f:
#       r = requests.get(url_name_file)
#       f.write(r.content)

def nc_pre_pro(ds):
  ds = xr.open_dataset(ds)
  return ds.where((-82 < ds.lon) & (ds.lon < -67) & (-19 < ds.lat) & (ds.lat < 2), drop=True)

nc_file = sorted(glob.glob("/content/drive/MyDrive/temporal/TerraClimate/*.nc"))
nc_file = [nc_pre_pro(i) for i in nc_file]
nc_file = xr.concat(nc_file, dim="time").sel(time=slice("1981-01-01","2019-12-31"))
nc_file = nc_file.drop("crs")

nc_file = nc_file.rename({"pet":"eo"})
encoding = {v: {'zlib': True, 'complevel': 5} for v in ["eo"]}

nc_file

nc_file.to_netcdf("/content/drive/MyDrive/PISCOeo_pm_big_data/Global_gridded_products/TERRACLIMATE_Eo_Peru_1981_2019_monthly_sum_ts.nc")

nc_file.resample(time="1Y").sum().to_netcdf("/content/drive/MyDrive/PISCOeo_pm_big_data/Global_gridded_products/TERRACLIMATE_Eo_Peru_1981_2019_yearly_sum_ts.nc")

nc_file.sel(time=slice("1981-01-01", "2010-12-31")).groupby('time.month').mean(dim="time").to_netcdf("/content/drive/MyDrive/PISCOeo_pm_big_data/Global_gridded_products/TERRACLIMATE_Eo_Peru_1981_2010_monthly_sum_mean.nc")